ALTER TABLE public.apontamentos 
  ADD COLUMN IF NOT EXISTS numero_tag TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS tag_inserted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS tag_inserted_by TEXT DEFAULT NULL;